from abc import ABC, abstractmethod
class BaseModel(ABC):
    @abstractmethod
    def fit(self,train_data,train_target,valid_data=None,valid_target=None): ...
    @abstractmethod
    def predict(self,data): ...
    @abstractmethod
    def save(self,path): ...
    @classmethod
    @abstractmethod
    def load(cls,path): ...

